### ISSUE TITLE
We need squad busters

### ISSUE THREAD

**Issue by Alzentane** [rclean/Supercell-jailbreak-Clash-of-Clans#5]
Squad busters update plz

**Comment by HarryPD168** [comment]
Please update

**Comment by Alzentane** [comment]
U need squad busters ?

**Comment by Alzentane** [comment]
https://www.mediafire.com/file/xnchc6hhtnxkeem/SquadBustersNJ.ipa/file

**Comment by HarryPD168** [comment]
Do you have contact information?

**Comment by HarryPD168** [comment]
> For who ?

You🤣

**Comment by Alzentane** [comment]
IG : zn21x
