### ISSUE TITLE
Path Brawl Stars?

### ISSUE THREAD

**Issue by SpyGdev** [rclean/Supercell-jailbreak-Clash-of-Clans#6]
Can you please patch Brawl Stars

**Comment by Alzentane** [comment]
https://www.mediafire.com/file/zptku3dnnk3cewk/Brawl_Stars_NJ.ipa/file

**Comment by SpyGdev** [comment]
Brawl Stars works perfectly

**Comment by lucasxtorrez** [comment]
can patch brawl stars??? pleaseee

**Comment by Alzentane** [comment]
> can patch brawl stars??? pleaseee

I can’t this script doesn’t work
